### ISSUE TITLE
Newly loaded chunk ... ... has no loaders registered...

### ISSUE THREAD

**Issue by brokiem** [ColinHDev/ActualAntiXRay#1]
**Is this normal/ok?** After installing this plugin then joining the server, console debug spammed with log ```Newly loaded chunk ... ... has no loaders registered, will be unloaded at next available opportunity```

![image](https://user-images.githubusercontent.com/61258338/182083184-ee2b505d-11ce-42b0-8970-c8e4d5e32c78.png)

## Steps to reproduce:
1. Install plugin
2. Enable console debug log
4. Join the server
5. See the spamming log

## Plugins (16):
ActualAntiXRay v1.0.0, BedrockEconomy v2.0.8, DevTools v1.15.0, EconomyLand v2.0.9, Essentials v1.0.0, FakePlayer v0.2.1, Fireworks v0.0.4.1, Hierarchy v2.0.1, JoinFireworks v2.0.0, PvPToggle v1.0.0, ScoreHud v7.0.1, ShopUI v1.0.0, SimpleNPC v3.0.3-dev, SimplePets v1.0.0-beta, VanillaElytra v1.4.0, VanillaGenerator v0.0.4

**Comment by ColinHDev** [comment]
Thank you for the report.

Yes, I already saw that on my test server.
But I only investigated it now, as it was now obvious that it was a problem with the plugin.

This bug just got fixed [here](https://github.com/ColinHDev/ActualAntiXRay/releases/tag/v1.0.1).
