### ISSUE TITLE
Bug Can’t open InvMenu Chest 

### ISSUE THREAD

**Issue by xodamcm** [ColinHDev/ActualAntiXRay#3]
Hi, i found this bug, with this plugin i can’t now open invmenu chest exemple: /ec , /stackstorage, etc, etc…

**Comment by xodamcm** [comment]
Update, i think the problem is with all chest and inventory

**Comment by ColinHDev** [comment]
I don't think it affects all block inventories or at least I am not able to reproduce this with normal blocks.
But I think, I know why this is happening with InvMenu. But I am really tired, so I will fix this tomorrow. ✌🏻

**Comment by ZippingBoat9588** [comment]
Same by me /invsee Not work

**Comment by ColinHDev** [comment]
This got fixed as of [`v1.0.3`](https://github.com/ColinHDev/ActualAntiXRay/releases/tag/v1.0.3)

**Comment by xodamcm** [comment]
Thx bro!! Fast, and ty for ur beautifful plugin!!!

**Comment by ColinHDev** [comment]
It was a relatively small fix and it took me way longer than I wanted it to, but I didn't have time till now.
