### ISSUE TITLE
Crash pm4

### ISSUE THREAD

**Issue by Ardaa001** [ColinHDev/ActualAntiXRay#4]
[Server thread/CRITICAL]: TypeError: "pocketmine\network\mcpe\NetworkSession::addToSendBuffer(): Argument #1 ($buffer) must be of type string, pocketmine\network\mcpe\protocol\UpdateBlockPacket given, called in C:\Users\Administrator\Desktop\test\plugins\ActualAntiXRay-main\src\ColinHDev\ActualAntiXRay\listener\DataPacketSendListener.php on line 89" (EXCEPTION) in "pmsrc/src/network/mcpe/NetworkSession" at line 503
--- Stack trace ---
  #0 plugins/ActualAntiXRay-main/src/ColinHDev/ActualAntiXRay/listener/DataPacketSendListener(89): pocketmine\network\mcpe\NetworkSession->addToSendBuffer(object pocketmine\network\mcpe\protocol\UpdateBlockPacket#151005)
  #1 pmsrc/src/event/RegisteredListener(60): ColinHDev\ActualAntiXRay\listener\DataPacketSendListener->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent#155401)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#155401)

**Comment by ColinHDev** [comment]
Fixed in https://github.com/ColinHDev/ActualAntiXRay/releases/tag/v1.0.5
