### ISSUE TITLE
PM5 :)

### ISSUE THREAD

**Issue by LadySara48** [ColinHDev/ActualAntiXRay#6]
I would be very happy if you have a chance to update this plugin to PocketMine 5 :)

**Comment by ColinHDev** [comment]
https://github.com/ColinHDev/ActualAntiXRay/releases/tag/v1.1.0 should work

**Comment by LadySara48** [comment]
Error: "Class "pocketmine\network\mcpe\convert\RuntimeBlockMapping" not found" (EXCEPTION) in "plugins/ActualAntiXRay.phar/src/ColinHDev/ActualAntiXRay/listener/DataPacketSendListener" at line 40

**Comment by LadySara48** [comment]
I've read the change logs RuntimeBlockMapping is now referred to as BlockTranslator. Also the file has been changed a lot so getInstance and some functions no longer exist
