### ISSUE TITLE
https://github.com/ColinHDev/ActualAntiXRay/releases/tag/v1.1.0 should work

### ISSUE THREAD

**Issue by LadySara48** [ColinHDev/ActualAntiXRay#7]
https://github.com/ColinHDev/ActualAntiXRay/releases/tag/v1.1.0 should work

_Originally posted by @ColinHDev in https://github.com/ColinHDev/ActualAntiXRay/issues/6#issuecomment-1627355990_
            
Error: "Class "pocketmine\network\mcpe\convert\RuntimeBlockMapping" not found" (EXCEPTION) in "plugins/ActualAntiXRay.phar/src/ColinHDev/ActualAntiXRay/listener/DataPacketSendListener" at line 40

**Comment by ColinHDev** [comment]
It should be fixed as of https://github.com/ColinHDev/ActualAntiXRay/releases/tag/v1.1.1
